name = "layarasa-web"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

# Konfigurasi Database Cloudflare D1
# Di Cloudflare Pages Dashboard:
# Project -> Settings -> Functions -> D1 database bindings:
# Variable name: DB
# D1 Database: layarasa-db
[[d1_databases]]
binding = "DB"
database_name = "layarasa-db"
database_id = "local-d1-id"
