name = "layarasa-web"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "elayarasa-db"
database_id = "0b135e59-54eb-4152-96c2-c5e351c3fc09"
